apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: builder-dockercfg-7pf84
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/internal-registry-pull-secret-ref: builder-dockercfg-7pf84
    creationTimestamp: "2025-06-04T13:45:49Z"
    name: builder
    namespace: wcdy-cert-frt
    resourceVersion: "1081262866"
    uid: 5b55ace3-3214-4136-aced-7f0b38d8b5d4
  secrets:
  - name: builder-dockercfg-7pf84
- apiVersion: v1
  imagePullSecrets:
  - name: default-dockercfg-vv7cn
  - name: quay-wcdy-pullsecret
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/internal-registry-pull-secret-ref: default-dockercfg-vv7cn
    creationTimestamp: "2025-06-04T13:45:49Z"
    name: default
    namespace: wcdy-cert-frt
    resourceVersion: "1081288144"
    uid: 75491133-3458-4226-825c-14c615a390e0
  secrets:
  - name: default-dockercfg-vv7cn
- apiVersion: v1
  imagePullSecrets:
  - name: deployer-dockercfg-qmb5z
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/internal-registry-pull-secret-ref: deployer-dockercfg-qmb5z
    creationTimestamp: "2025-06-04T13:45:49Z"
    name: deployer
    namespace: wcdy-cert-frt
    resourceVersion: "1081262862"
    uid: 5cf751e1-7c23-454a-9df6-353bb5901e9d
  secrets:
  - name: deployer-dockercfg-qmb5z
kind: List
metadata:
  resourceVersion: ""
